[package]
name = "wallet"
version.workspace = true
edition.workspace = true

[dependencies]
bs58 = { workspace = true }
crypto = { path = "../crypto" }
libp2p = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }