[package]
name = "operation"
version.workspace = true
edition.workspace = true

[dependencies]
tx = { path = "../tx" }
balance = { path = "../balance" }
stake = { path = "../stake" }
common = { path = "../common" }

[dev-dependencies]
wallet = { path = "../wallet" }
