[package]
name = "state"
version.workspace = true
edition.workspace = true

[dependencies]
block = { path = "../block" }
db = { path = "../db" }
stake = { path = "../stake" }
operation = { path = "../operation" }
balance = { path = "../balance" }
rs_merkle = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tx = { path = "../tx" }
wallet = { path = "../wallet" }
log = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }