[package]
name = "state"
version.workspace = true
edition.workspace = true

[dependencies]
block = { path = "../block" }
bigdecimal = { workspace = true }
db = { path = "../db" }
rs_merkle = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
tx = { path = "../tx" }
wallet = { path = "../wallet" }
log = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }