[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
bigdecimal = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
