[package]
name = "crypto"
version.workspace = true
edition.workspace = true

[dependencies]
argon2 = { workspace = true }
libsecp256k1 = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
aes-gcm = { workspace = true }
