[package]
name = "crypto"
version.workspace = true
edition.workspace = true

[dependencies]
argon2 = { workspace = true }
libp2p = { workspace = true }
rand = { workspace = true }
bs58 = { workspace = true }
aes-gcm = { workspace = true }